version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    env_file:
      - "postgres-prod.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: "."
    env_file: "server-prod.env"
    ports:
      - "3000:3000"
    links:
      - "redis:redis"
      - "postgres:postgres"

volumes:
  pgdata: null
  
