version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    env_file:
      - "postgres-prod.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certs/:/etc/nginx/ssl/live/
  server:
    build: "."
    env_file: "server-prod.env"
    links:
      - "redis:redis"
      - "postgres:postgres"


volumes:
  pgdata: null
