version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - "postgres.env"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  webserver:
    image: "."
    env_file: "prod.env"
    links:
      - "redis:redis"
      - "postgres:postgres"
