version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - "postgres/postgres-prod.env"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
      - ./postgres/init-scripts/:/docker-entrypoint-initdb.d/ # For database creation scripts
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  influxdb:
    image: influxdb:latest
    env_file:
      - "influxdb/influxdb-prod.env"
    volumes:
      - ./influxdb/data/:/var/lib/influxdb2
      - ./influxdb/config/:/etc/influxdb2
  server:
    build: 
      context: "./src"
      dockerfile: "server/Dockerfile"
    env_file: "src/server/server-prod.env"
  collector:
    build: 
      context: "."
      dockerfile: "src/collector/Dockerfile"
    env_file: "src/collector/collector-prod.env"
