version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    env_file:
      - "postgres-prod.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/cerbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
  server:
    build: "."
    env_file: "server-prod.env"
    ports:
      - "3000:3000"
    links:
      - "redis:redis"
      - "postgres:postgres"

volumes:
  pgdata: null
