version: "3.9"

services:
  redis:
    image: redis
  postgres:
    image: postgres
    env_file:
      - "postgres-prod.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  influxdb:
    image: influxdb:latest
    env_file:
      - "influxdb-prod.env"
    volumes:
      - influxdata:/var/lib/influxdb2
      - influxconfig:/etc/influxdb2
  server:
    build: "."
    env_file: "server-prod.env"

volumes:
  pgdata: null
  influxdata: null
  influxconfig: null
