version: "3.9"
   
services:
  redis:
    image: redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - "postgres.env"
  webserver:
    image: "."
    env_file: "prod.env"
    links:
      - "redis:redis"
      - "postgres:postgres"