[package]
name = "database"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4.11"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]

